# Copyright (c) Mainflux
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.influxdbjson.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-influxdb-writer
spec:
  selector:
    app: {{ .Release.Name }}
    component: influxdb-writer
  ports:
    - port: {{ .Values.influxdbjson.writer.httpPort }}
      protocol: TCP
      name: {{ .Release.Name }}-influxdb-writer-{{ .Values.influxdbjson.writer.httpPort }}
{{- end }}
